[package]
name = "cashflow"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
rust_decimal = "1"
rust_decimal_macros = "1"
