mortgage:
  deduction_amount: 123.45
  deduction_day: 1
current_account:
  main:
    position:
      date: "2025-01-01"
      balance: 10000.00
currency_symbol: "£"
salary:
  amount: 2500.00
  day: 26

