start_date: "2025-01-01"
transactions:
  - type: mortgage
    deduction_amount: 123.45
    deduction_day: 1
  - type: salary
    amount: 2500.00
    day: 26
accounts:
  main: 10000.00
  mortgage: 500000.00
currency_symbol: "£"

